name: Terraform Deployment

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  pull_request:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2  # Specify your AWS region
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}  # Use the secret here
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}  # Use the secret here

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"  # Use a variable file if needed

      - name: Terraform Apply
        run: terraform apply -auto-approve